import '../risk_engine.dart';

enum CenterType {
  dentalInstitute,
  oncologyCentre,
  oralMedicineOmfs,
  communityScreening,
}

extension CenterTypeX on CenterType {
  String get label => switch (this) {
    CenterType.dentalInstitute => 'Dental Institute / College',
    CenterType.oncologyCentre => 'Comprehensive Cancer Centre',
    CenterType.oralMedicineOmfs => 'Oral Medicine & OMFS Dept',
    CenterType.communityScreening => 'Community Health Centre',
  };
}

class ScreeningCenter {
  const ScreeningCenter({
    required this.id,
    required this.name,
    required this.type,
    required this.city,
    required this.state,
    required this.address,
    required this.phone,
    required this.timings,
    required this.services,
  });

  final String id;
  final String name;
  final CenterType type;
  final String city;
  final String state;
  final String address;
  final String phone;
  final String timings;
  final List<String> services;
}

class ScreeningCentersCatalog {
  const ScreeningCentersCatalog._();

  static const List<ScreeningCenter> centers = [
    ScreeningCenter(
      id: 'cids_coorg',
      name: 'Coorg Institute of Dental Sciences (CIDS)',
      type: CenterType.dentalInstitute,
      city: 'Coorg (Virajpet)',
      state: 'Karnataka',
      address: 'K.K. Campus, Maggula Village, Virajpet, Karnataka 571218',
      phone: '+91 8274 256479',
      timings: 'Monday – Saturday: 9:00 AM – 4:00 PM',
      services: [
        'Oral Pathology & Biopsy Services',
        'Oral Medicine & Radiology OPD',
        'Oral & Maxillofacial Surgery (OMFS)',
        'Free Cancer Screening & Tobacco Cessation',
      ],
    ),
    ScreeningCenter(
      id: 'kidwai_bangalore',
      name: 'Kidwai Memorial Institute of Oncology',
      type: CenterType.oncologyCentre,
      city: 'Bengaluru',
      state: 'Karnataka',
      address: 'Dr. M.H. Marigowda Road, Hombegowda Nagar, Bengaluru 560029',
      phone: '080-26094000',
      timings: 'OPD: Monday – Saturday 8:00 AM – 2:00 PM',
      services: [
        'Head & Neck Surgical Oncology',
        'Radiation Oncology & Chemotherapy',
        'Tumor Board Evaluation',
        'Rehabilitation & Speech Therapy',
      ],
    ),
    ScreeningCenter(
      id: 'tata_memorial_mumbai',
      name: 'Tata Memorial Centre (TMC)',
      type: CenterType.oncologyCentre,
      city: 'Mumbai',
      state: 'Maharashtra',
      address: 'Dr. Ernest Borges Road, Parel, Mumbai 400012',
      phone: '022-24177000',
      timings: 'Monday – Friday: 8:00 AM – 5:00 PM',
      services: [
        'National Apex Cancer Care & Research',
        'Microvascular Reconstructive Surgery',
        'Histopathology & Molecular Diagnostics',
        'Palliative & Psychosocial Care',
      ],
    ),
    ScreeningCenter(
      id: 'gdcri_bangalore',
      name: 'Government Dental College & Research Institute (GDCRI)',
      type: CenterType.dentalInstitute,
      city: 'Bengaluru',
      state: 'Karnataka',
      address: 'Victoria Hospital Campus, Fort, Bengaluru 560002',
      phone: '080-26705053',
      timings: 'Monday – Saturday: 9:00 AM – 3:30 PM',
      services: [
        'Specialist Oral Medicine Consultations',
        'Incisional & Punch Biopsy',
        'Management of Oral Pre-Cancers (OSMF/Leukoplakia)',
      ],
    ),
    ScreeningCenter(
      id: 'aiims_delhi',
      name: 'Dr. B.R. Ambedkar Institute Rotary Cancer Hospital (AIIMS)',
      type: CenterType.oncologyCentre,
      city: 'New Delhi',
      state: 'Delhi',
      address: 'Ansari Nagar, New Delhi 110029',
      phone: '011-26588500',
      timings: 'Monday – Saturday: 8:30 AM – 1:00 PM',
      services: [
        'Multidisciplinary Head & Neck Oncology',
        'Comprehensive Surgical & Medical Oncology',
        'Post-treatment Rehabilitation & Nutrition',
      ],
    ),
  ];

  /// Generates a standardized clinical referral letter for outpatient presentation
  static String generateReferralLetter({
    required String patientName,
    required String patientId,
    required int? age,
    required String? gender,
    required RiskResult? result,
    required String? lesionSite,
    required int? lesionDurationDays,
    required List<String> reportedSymptoms,
  }) {
    final buffer = StringBuffer();
    final now = DateTime.now();

    buffer.writeln('====================================================');
    buffer.writeln('    ORAL CANCER CARECONNECT — CLINICAL REFERRAL SLIP');
    buffer.writeln('====================================================');
    buffer.writeln('Date of Referral: ${now.day}/${now.month}/${now.year}');
    buffer.writeln('Generated by: OralCare Pilot Assessment System');
    buffer.writeln('Status: CONFIDENTIAL MEDICAL REFERRAL');
    buffer.writeln('----------------------------------------------------');
    buffer.writeln(
      'TO: The Attending Clinician / Head & Neck OPD / Oral Medicine',
    );
    buffer.writeln('RE: Clinical Examination & Specialist Assessment');
    buffer.writeln('----------------------------------------------------');
    buffer.writeln('PATIENT DEMOGRAPHICS:');
    buffer.writeln(
      '  Patient ID: ${patientId.isNotEmpty ? patientId : "Not registered"}',
    );
    buffer.writeln(
      '  Name: ${patientName.isNotEmpty ? patientName : "Anonymous Patient"}',
    );
    buffer.writeln(
      '  Age: ${age ?? "Unknown"} years  |  Gender: ${gender ?? "Unspecified"}',
    );
    buffer.writeln('----------------------------------------------------');
    buffer.writeln('ASSESSMENT SUMMARY:');
    if (result != null) {
      buffer.writeln(
        '  Provisional Risk Band: ${result.category.label.toUpperCase()} (Score: ${result.totalScore})',
      );
      buffer.writeln(
        '  Urgency Status: ${result.outputState.headline.toUpperCase()}',
      );
      if (result.redFlagPresent) {
        buffer.writeln(
          '  RED FLAG TRIGGER: Persistent lesion or alarming clinical signs detected.',
        );
      }
    } else {
      buffer.writeln(
        '  Assessment: Patient reported active oral lesion requiring direct evaluation.',
      );
    }
    buffer.writeln('----------------------------------------------------');
    buffer.writeln('LESION & SYMPTOMS REPORTED:');
    buffer.writeln('  Site: ${lesionSite ?? "Oral cavity site of concern"}');
    buffer.writeln(
      '  Reported Duration: ${lesionDurationDays != null ? "$lesionDurationDays days" : "Unknown"}',
    );
    if (reportedSymptoms.isNotEmpty) {
      buffer.writeln('  Symptoms: ${reportedSymptoms.join(", ")}');
    }
    buffer.writeln('----------------------------------------------------');
    buffer.writeln('RECOMMENDED CLINICAL ACTION:');
    buffer.writeln(
      '  1. Comprehensive intraoral visual and palpation examination.',
    );
    buffer.writeln('  2. Assessment of regional cervical lymphadenopathy.');
    buffer.writeln(
      '  3. Incisional biopsy / Toluidine blue / Diagnostic imaging if indicated.',
    );
    buffer.writeln(
      '  4. Structured tobacco and areca nut cessation counseling.',
    );
    buffer.writeln('----------------------------------------------------');
    buffer.writeln('CLINICAL SAFETY DISCLAIMER:');
    buffer.writeln(
      'This referral slip is generated from patient-reported symptoms',
    );
    buffer.writeln(
      'and provisional screening algorithms. It does NOT constitute a',
    );
    buffer.writeln(
      'confirmed diagnosis or staging of Oral Squamous Cell Carcinoma.',
    );
    buffer.writeln('====================================================');

    return buffer.toString();
  }
}
